import { forwardRef } from "react";
import { View, Text, Image, StyleSheet } from "react-native";
import { useTheme } from "@/providers/theme-provider";
import { Quote } from "lucide-react-native";
import { type TranscriptSegment } from "@teach-player/shared";

interface QuoteShareCardProps {
  segment: TranscriptSegment;
  thumbnailUrl?: string;
  videoTitle: string;
}

export const QuoteShareCard = forwardRef<View, QuoteShareCardProps>(({ segment, thumbnailUrl, videoTitle }, ref) => {
  const { theme, isDark } = useTheme();

  return (
    <View ref={ref} style={[styles.container, { backgroundColor: isDark ? "#1A1A1A" : "#FFFFFF" }]}>
      <View style={styles.content}>
        {/* Top Quote Icon */}
        <Quote color={theme.colors.accent} size={32} style={styles.quoteIcon} />

        {/* Text Section */}
        <View style={styles.textContainer}>
          <Text style={[styles.englishText, { color: theme.colors.text }]}>
            {segment.text}
          </Text>
          {segment.text_zh ? (
            <Text style={[styles.chineseText, { color: theme.colors.muted }]}>
              {segment.text_zh}
            </Text>
          ) : null}
        </View>

        {/* Video Info Section */}
        <View style={styles.footerContainer}>
          {thumbnailUrl ? (
            <Image source={{ uri: thumbnailUrl }} style={styles.thumbnail} />
          ) : (
            <View style={[styles.thumbnail, styles.thumbnailFallback]}>
              <Text style={styles.thumbnailFallbackText}>TP</Text>
            </View>
          )}
          <View style={styles.footerInfo}>
            <Text numberOfLines={2} style={[styles.videoTitle, { color: theme.colors.text }]}>
              {videoTitle}
            </Text>
            <Text style={[styles.brandText, { color: theme.colors.accent }]}>
              Generated by Teach Player
            </Text>
          </View>
        </View>
      </View>
    </View>
  );
});

QuoteShareCard.displayName = "QuoteShareCard";

const styles = StyleSheet.create({
  container: {
    width: 400,
    padding: 24,
    // Add shadow so the captured image feels like a card if not full bleed
  },
  content: {
    backgroundColor: "transparent",
    gap: 24,
  },
  quoteIcon: {
    marginBottom: 8,
    opacity: 0.8,
  },
  textContainer: {
    gap: 12,
  },
  englishText: {
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 34,
  },
  chineseText: {
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 24,
  },
  footerContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(128,128,128,0.2)",
    paddingTop: 16,
  },
  thumbnail: {
    width: 64,
    height: 40,
    borderRadius: 6,
  },
  thumbnailFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DFFF00",
  },
  thumbnailFallbackText: {
    color: "#0A1A00",
    fontSize: 13,
    fontWeight: "900",
  },
  footerInfo: {
    flex: 1,
    gap: 4,
  },
  videoTitle: {
    fontSize: 13,
    fontWeight: "600",
  },
  brandText: {
    fontSize: 11,
    fontWeight: "800",
  },
});
