/**
 * 统一跨平台 Schema
 *
 * 标准化 YouTube 和 Bilibili 的 transcript/metadata 格式，
 * 使添加新平台（TikTok、播客等）变得简单。
 *
 * @module types/unified
 */

import { z } from "zod";

// ============================================================================
// 1. 统一平台标识
// ============================================================================

/** 支持的平台 */
export const PlatformSchema = z.enum(["youtube", "bilibili", "tiktok", "podcast", "other"]);
export type Platform = z.infer<typeof PlatformSchema>;

// ============================================================================
// 2. 统一元数据 Schema
// ============================================================================

/** 统一元数据 - 所有平台共享 */
export const UnifiedMetadataSchema = z.object({
  /** 平台标识 */
  platform: PlatformSchema,

  /** 视频/内容 ID（平台原生格式） */
  videoId: z.string().min(1),

  /** 标题 */
  title: z.string().min(1),

  /** 作者/创作者名称 */
  author: z.string().optional(),

  /** 时长（秒） */
  duration: z.number().nonnegative().optional(),

  /** 缩略图 URL */
  thumbnail: z.string().url().optional(),

  /** 内容语言（ISO 639-1） */
  language: z.string().length(2).optional(),

  /** 原始平台 URL */
  originalUrl: z.string().url().optional(),

  /** 平台特定的额外字段 */
  extra: z.record(z.unknown()).optional(),
});

export type UnifiedMetadata = z.infer<typeof UnifiedMetadataSchema>;

// ============================================================================
// 3. 统一 Transcript Segment Schema
// ============================================================================

/** 统一字幕段 - 所有平台共享 */
export const UnifiedSegmentSchema = z.object({
  /** 开始时间（秒） */
  startTime: z.number().nonnegative(),

  /** 结束时间（秒） */
  endTime: z.number().positive(),

  /** 原始文本 */
  text: z.string().min(1),

  /** 翻译文本（可选） */
  textZh: z.string().optional(),

  /** 置信度分数（0-1，可选） */
  confidence: z.number().min(0).max(1).optional(),

  /** 说话人标识（可选） */
  speaker: z.string().optional(),
});

export type UnifiedSegment = z.infer<typeof UnifiedSegmentSchema>;

// ============================================================================
// 4. 统一 Transcript Schema
// ============================================================================

/** 统一字幕 - 包含元数据和所有段落 */
export const UnifiedTranscriptSchema = z.object({
  /** 元数据 */
  metadata: UnifiedMetadataSchema,

  /** 字幕段落列表 */
  segments: z.array(UnifiedSegmentSchema).min(0),

  /** 字幕来源（用于调试） */
  source: z.object({
    /** 提供者名称 */
    provider: z.string(),

    /** 是否为自动生成 */
    isAutoGenerated: z.boolean().optional(),

    /** 原始语言 */
    originalLanguage: z.string().optional(),

    /** 提取耗时（毫秒） */
    extractionTimeMs: z.number().optional(),
  }).optional(),

  /** 缓存信息 */
  cached: z.boolean().optional(),
});

export type UnifiedTranscript = z.infer<typeof UnifiedTranscriptSchema>;

// ============================================================================
// 5. 平台特定转换器
// ============================================================================

/**
 * 将 YouTube 元数据转换为统一格式
 */
export function fromYouTubeMetadata(data: {
  videoId: string;
  title: string;
  authorName?: string;
  thumbnailUrl?: string;
  providerUrl?: string;
}): UnifiedMetadata {
  return {
    platform: "youtube",
    videoId: data.videoId,
    title: data.title,
    author: data.authorName,
    thumbnail: data.thumbnailUrl,
    originalUrl: `https://www.youtube.com/watch?v=${data.videoId}`,
  };
}

/**
 * 将 Bilibili 元数据转换为统一格式
 */
export function fromBilibiliMetadata(data: {
  videoId: string;
  title: string;
  authorName?: string;
  thumbnailUrl?: string;
  description?: string;
  cid?: number;
  duration?: number;
}): UnifiedMetadata {
  return {
    platform: "bilibili",
    videoId: data.videoId,
    title: data.title,
    author: data.authorName,
    duration: data.duration,
    thumbnail: data.thumbnailUrl,
    originalUrl: `https://www.bilibili.com/video/${data.videoId}`,
    extra: {
      description: data.description,
      cid: data.cid,
    },
  };
}

/**
 * 将 YouTube transcript segments 转换为统一格式
 */
export function fromYouTubeSegments(segments: Array<{
  startTime: number;
  endTime: number;
  text: string;
  textZh?: string;
}>): UnifiedSegment[] {
  return segments.map(s => ({
    startTime: s.startTime,
    endTime: s.endTime,
    text: s.text,
    textZh: s.textZh,
  }));
}

/**
 * 将 Bilibili transcript segments 转换为统一格式
 */
export function fromBilibiliSegments(segments: Array<{
  startTime: number;
  endTime: number;
  text: string;
  textZh?: string;
}>): UnifiedSegment[] {
  return segments.map(s => ({
    startTime: s.startTime,
    endTime: s.endTime,
    text: s.text,
    textZh: s.textZh,
  }));
}

/**
 * 将统一格式转换回旧格式（兼容性）
 */
export function toLegacyFormat(unified: UnifiedTranscript): {
  metadata: {
    videoId: string;
    title: string;
    authorName?: string;
    thumbnailUrl?: string;
    providerUrl?: string;
  };
  transcript: Array<{
    startTime: number;
    endTime: number;
    text: string;
    textZh?: string;
  }>;
} {
  return {
    metadata: {
      videoId: unified.metadata.videoId,
      title: unified.metadata.title,
      authorName: unified.metadata.author,
      thumbnailUrl: unified.metadata.thumbnail,
      providerUrl: unified.metadata.originalUrl,
    },
    transcript: unified.segments.map(s => ({
      startTime: s.startTime,
      endTime: s.endTime,
      text: s.text,
      textZh: s.textZh,
    })),
  };
}

// ============================================================================
// 6. 工具函数
// ============================================================================

/**
 * 计算字幕总时长（秒）
 */
export function calculateDuration(segments: UnifiedSegment[]): number {
  if (segments.length === 0) return 0;
  const lastSegment = segments[segments.length - 1];
  return lastSegment.endTime;
}

/**
 * 计算字幕总字符数
 */
export function calculateTotalChars(segments: UnifiedSegment[]): number {
  return segments.reduce((sum, s) => sum + s.text.length, 0);
}

/**
 * 检测字幕语言（简单启发式）
 */
export function detectLanguage(segments: UnifiedSegment[]): string {
  const allText = segments.map(s => s.text).join(" ");
  const chineseChars = allText.match(/[\u4e00-\u9fff]/g)?.length ?? 0;
  const totalChars = allText.length;

  if (totalChars === 0) return "unknown";
  if (chineseChars / totalChars > 0.3) return "zh";
  return "en";
}

/**
 * 过滤空段落并合并连续段落
 */
export function cleanSegments(segments: UnifiedSegment[]): UnifiedSegment[] {
  return segments
    .filter(s => s.text.trim().length > 0)
    .map(s => ({
      ...s,
      text: s.text.trim(),
    }));
}
